### ISSUE TITLE
Note that some are tricky

### ISSUE THREAD

**Issue by matkoniecz** [mnalis/StreetComplete-taginfo-categorize#4]
For example `inscription`

If someone made a common bad choice and mapped shop and building as one object then this tag can refer to something on building, unrelated to the shop.

In principle, support for such car could be implemented (for example asking user is given inscription still present) but it works be nasty to implement.

And for GNIS id it is even worse as there is no direct human readable form (and putting GNIS database into SC would be silly)

**Comment by mnalis** [comment]
Good point, I've moved `inscription` to "keep" section then. If one day even smarter handling is implemented (your suggestion, or for example to remove it only if there is no `building` tag), that would be great, but otherwise, better be safe than sorry (the whole point of the conversion to "delete only things you understand and are sure will not be missed").

On the other hand, `gnis:feature_id` (and `gnis:created` etc) are used (in tags that we process) mostly on `amenity=post_office` (12161 times) which seems to me according to https://wiki.openstreetmap.org/wiki/USGS_GNIS should be removed if post office is no longer there? (There are also used on few `craft`, but it is only 13 uses worldwide but still managed to make `0.01%` of combined tags, and similar logic would apply anyway?)

So I'd tend to leave `gnis:*` in "to remove" section.

Let me know if that is OK (or if I misunderstood something), or if you have more ideas to curate this list. Thanks again for taking the time to look into it!

**Comment by matkoniecz** [comment]
Seems Ok!
